language: c
os: linux
sudo: false
dist: trusty
addons:
  firefox: latest
before_install:
  - git clone --depth 1 git://github.com/astropy/ci-helpers.git
  - source ci-helpers/travis/setup_conda.sh
  - conda env update -n base --file environment.yml
install:
  - bash postBuild
script:
  - source activate base && jlpm test
